#include "cpu_ops.h"
#include <stddef.h>
// 256-entry dispatch table mapping each opcode to its cycle pattern and operation.
// Ref: https://www.masswerk.at/6502/6502_instruction_set.html
// Ref: https://www.nesdev.org/undocumented_opcodes.txt

const OpcodeEntry opcode_table[256] = {

    [0x00] = { PAT_BRK,       NULL     },  // BRK
    [0x01] = { PAT_IZX_READ,  op_ora   },  // ORA (d,X)
    [0x03] = { PAT_IZX_RMW,   op_slo   },  // *SLO (d,X)
    [0x04] = { PAT_ZPG_READ,  op_nop   },  // *NOP d
    [0x05] = { PAT_ZPG_READ,  op_ora   },  // ORA d
    [0x06] = { PAT_ZPG_RMW,   op_asl   },  // ASL d
    [0x07] = { PAT_ZPG_RMW,   op_slo   },  // *SLO d
    [0x08] = { PAT_PUSH,      op_php   },  // PHP
    [0x09] = { PAT_IMMEDIATE, op_ora   },  // ORA #
    [0x0A] = { PAT_IMPLIED,   op_asl_acc }, // ASL A
    [0x0B] = { PAT_IMMEDIATE, op_anc   },  // *ANC #
    [0x0C] = { PAT_ABS_READ,  op_nop   },  // *NOP a
    [0x0D] = { PAT_ABS_READ,  op_ora   },  // ORA a
    [0x0E] = { PAT_ABS_RMW,   op_asl   },  // ASL a
    [0x0F] = { PAT_ABS_RMW,   op_slo   },  // *SLO a

    [0x10] = { PAT_BRANCH,    op_bpl   },  // BPL
    [0x11] = { PAT_IZY_READ,  op_ora   },  // ORA (d),Y
    [0x13] = { PAT_IZY_RMW,   op_slo   },  // *SLO (d),Y
    [0x14] = { PAT_ZPX_READ,  op_nop   },  // *NOP d,X
    [0x15] = { PAT_ZPX_READ,  op_ora   },  // ORA d,X
    [0x16] = { PAT_ZPX_RMW,   op_asl   },  // ASL d,X
    [0x17] = { PAT_ZPX_RMW,   op_slo   },  // *SLO d,X
    [0x18] = { PAT_IMPLIED,   op_clc   },  // CLC
    [0x19] = { PAT_ABY_READ,  op_ora   },  // ORA a,Y
    [0x1A] = { PAT_IMPLIED,   op_nop   },  // *NOP
    [0x1B] = { PAT_ABY_RMW,   op_slo   },  // *SLO a,Y
    [0x1C] = { PAT_ABX_READ,  op_nop   },  // *NOP a,X
    [0x1D] = { PAT_ABX_READ,  op_ora   },  // ORA a,X
    [0x1E] = { PAT_ABX_RMW,   op_asl   },  // ASL a,X
    [0x1F] = { PAT_ABX_RMW,   op_slo   },  // *SLO a,X

    [0x20] = { PAT_JSR,       NULL     },  // JSR
    [0x21] = { PAT_IZX_READ,  op_and   },  // AND (d,X)
    [0x23] = { PAT_IZX_RMW,   op_rla   },  // *RLA (d,X)
    [0x24] = { PAT_ZPG_READ,  op_bit   },  // BIT d
    [0x25] = { PAT_ZPG_READ,  op_and   },  // AND d
    [0x26] = { PAT_ZPG_RMW,   op_rol   },  // ROL d
    [0x27] = { PAT_ZPG_RMW,   op_rla   },  // *RLA d
    [0x28] = { PAT_PULL,      op_plp   },  // PLP
    [0x29] = { PAT_IMMEDIATE, op_and   },  // AND #
    [0x2A] = { PAT_IMPLIED,   op_rol_acc }, // ROL A
    [0x2B] = { PAT_IMMEDIATE, op_anc   },  // *ANC #
    [0x2C] = { PAT_ABS_READ,  op_bit   },  // BIT a
    [0x2D] = { PAT_ABS_READ,  op_and   },  // AND a
    [0x2E] = { PAT_ABS_RMW,   op_rol   },  // ROL a
    [0x2F] = { PAT_ABS_RMW,   op_rla   },  // *RLA a

    [0x30] = { PAT_BRANCH,    op_bmi   },  // BMI
    [0x31] = { PAT_IZY_READ,  op_and   },  // AND (d),Y
    [0x33] = { PAT_IZY_RMW,   op_rla   },  // *RLA (d),Y
    [0x34] = { PAT_ZPX_READ,  op_nop   },  // *NOP d,X
    [0x35] = { PAT_ZPX_READ,  op_and   },  // AND d,X
    [0x36] = { PAT_ZPX_RMW,   op_rol   },  // ROL d,X
    [0x37] = { PAT_ZPX_RMW,   op_rla   },  // *RLA d,X
    [0x38] = { PAT_IMPLIED,   op_sec   },  // SEC
    [0x39] = { PAT_ABY_READ,  op_and   },  // AND a,Y
    [0x3A] = { PAT_IMPLIED,   op_nop   },  // *NOP
    [0x3B] = { PAT_ABY_RMW,   op_rla   },  // *RLA a,Y
    [0x3C] = { PAT_ABX_READ,  op_nop   },  // *NOP a,X
    [0x3D] = { PAT_ABX_READ,  op_and   },  // AND a,X
    [0x3E] = { PAT_ABX_RMW,   op_rol   },  // ROL a,X
    [0x3F] = { PAT_ABX_RMW,   op_rla   },  // *RLA a,X

    [0x40] = { PAT_RTI,       NULL     },  // RTI
    [0x41] = { PAT_IZX_READ,  op_eor   },  // EOR (d,X)
    [0x43] = { PAT_IZX_RMW,   op_sre   },  // *SRE (d,X)
    [0x44] = { PAT_ZPG_READ,  op_nop   },  // *NOP d
    [0x45] = { PAT_ZPG_READ,  op_eor   },  // EOR d
    [0x46] = { PAT_ZPG_RMW,   op_lsr   },  // LSR d
    [0x47] = { PAT_ZPG_RMW,   op_sre   },  // *SRE d
    [0x48] = { PAT_PUSH,      op_pha   },  // PHA
    [0x49] = { PAT_IMMEDIATE, op_eor   },  // EOR #
    [0x4A] = { PAT_IMPLIED,   op_lsr_acc }, // LSR A
    [0x4B] = { PAT_IMMEDIATE, op_alr   },  // *ALR #
    [0x4C] = { PAT_JMP_ABS,   NULL     },  // JMP a
    [0x4D] = { PAT_ABS_READ,  op_eor   },  // EOR a
    [0x4E] = { PAT_ABS_RMW,   op_lsr   },  // LSR a
    [0x4F] = { PAT_ABS_RMW,   op_sre   },  // *SRE a

    [0x50] = { PAT_BRANCH,    op_bvc   },  // BVC
    [0x51] = { PAT_IZY_READ,  op_eor   },  // EOR (d),Y
    [0x53] = { PAT_IZY_RMW,   op_sre   },  // *SRE (d),Y
    [0x54] = { PAT_ZPX_READ,  op_nop   },  // *NOP d,X
    [0x55] = { PAT_ZPX_READ,  op_eor   },  // EOR d,X
    [0x56] = { PAT_ZPX_RMW,   op_lsr   },  // LSR d,X
    [0x57] = { PAT_ZPX_RMW,   op_sre   },  // *SRE d,X
    [0x58] = { PAT_IMPLIED,   op_cli   },  // CLI
    [0x59] = { PAT_ABY_READ,  op_eor   },  // EOR a,Y
    [0x5A] = { PAT_IMPLIED,   op_nop   },  // *NOP
    [0x5B] = { PAT_ABY_RMW,   op_sre   },  // *SRE a,Y
    [0x5C] = { PAT_ABX_READ,  op_nop   },  // *NOP a,X
    [0x5D] = { PAT_ABX_READ,  op_eor   },  // EOR a,X
    [0x5E] = { PAT_ABX_RMW,   op_lsr   },  // LSR a,X
    [0x5F] = { PAT_ABX_RMW,   op_sre   },  // *SRE a,X

    [0x60] = { PAT_RTS,       NULL     },  // RTS
    [0x61] = { PAT_IZX_READ,  op_adc   },  // ADC (d,X)
    [0x63] = { PAT_IZX_RMW,   op_rra   },  // *RRA (d,X)
    [0x64] = { PAT_ZPG_READ,  op_nop   },  // *NOP d
    [0x65] = { PAT_ZPG_READ,  op_adc   },  // ADC d
    [0x66] = { PAT_ZPG_RMW,   op_ror   },  // ROR d
    [0x67] = { PAT_ZPG_RMW,   op_rra   },  // *RRA d
    [0x68] = { PAT_PULL,      op_pla   },  // PLA
    [0x69] = { PAT_IMMEDIATE, op_adc   },  // ADC #
    [0x6A] = { PAT_IMPLIED,   op_ror_acc }, // ROR A
    [0x6B] = { PAT_IMMEDIATE, op_arr   },  // *ARR #
    [0x6C] = { PAT_JMP_IND,   NULL     },  // JMP (a)
    [0x6D] = { PAT_ABS_READ,  op_adc   },  // ADC a
    [0x6E] = { PAT_ABS_RMW,   op_ror   },  // ROR a
    [0x6F] = { PAT_ABS_RMW,   op_rra   },  // *RRA a

    [0x70] = { PAT_BRANCH,    op_bvs   },  // BVS
    [0x71] = { PAT_IZY_READ,  op_adc   },  // ADC (d),Y
    [0x73] = { PAT_IZY_RMW,   op_rra   },  // *RRA (d),Y
    [0x74] = { PAT_ZPX_READ,  op_nop   },  // *NOP d,X
    [0x75] = { PAT_ZPX_READ,  op_adc   },  // ADC d,X
    [0x76] = { PAT_ZPX_RMW,   op_ror   },  // ROR d,X
    [0x77] = { PAT_ZPX_RMW,   op_rra   },  // *RRA d,X
    [0x78] = { PAT_IMPLIED,   op_sei   },  // SEI
    [0x79] = { PAT_ABY_READ,  op_adc   },  // ADC a,Y
    [0x7A] = { PAT_IMPLIED,   op_nop   },  // *NOP
    [0x7B] = { PAT_ABY_RMW,   op_rra   },  // *RRA a,Y
    [0x7C] = { PAT_ABX_READ,  op_nop   },  // *NOP a,X
    [0x7D] = { PAT_ABX_READ,  op_adc   },  // ADC a,X
    [0x7E] = { PAT_ABX_RMW,   op_ror   },  // ROR a,X
    [0x7F] = { PAT_ABX_RMW,   op_rra   },  // *RRA a,X

    [0x80] = { PAT_IMMEDIATE, op_nop   },  // *NOP #
    [0x81] = { PAT_IZX_WRITE, op_sta   },  // STA (d,X)
    [0x82] = { PAT_IMMEDIATE, op_nop   },  // *NOP #
    [0x83] = { PAT_IZX_WRITE, op_sax   },  // *SAX (d,X)
    [0x84] = { PAT_ZPG_WRITE, op_sty   },  // STY d
    [0x85] = { PAT_ZPG_WRITE, op_sta   },  // STA d
    [0x86] = { PAT_ZPG_WRITE, op_stx   },  // STX d
    [0x87] = { PAT_ZPG_WRITE, op_sax   },  // *SAX d
    [0x88] = { PAT_IMPLIED,   op_dey   },  // DEY
    [0x89] = { PAT_IMMEDIATE, op_nop   },  // *NOP #
    [0x8A] = { PAT_IMPLIED,   op_txa   },  // TXA
    [0x8C] = { PAT_ABS_WRITE, op_sty   },  // STY a
    [0x8D] = { PAT_ABS_WRITE, op_sta   },  // STA a
    [0x8E] = { PAT_ABS_WRITE, op_stx   },  // STX a
    [0x8F] = { PAT_ABS_WRITE, op_sax   },  // *SAX a
   
    [0x90] = { PAT_BRANCH,    op_bcc   },  // BCC
    [0x91] = { PAT_IZY_WRITE, op_sta   },  // STA (d),Y
    [0x94] = { PAT_ZPX_WRITE, op_sty   },  // STY d,X
    [0x95] = { PAT_ZPX_WRITE, op_sta   },  // STA d,X
    [0x96] = { PAT_ZPY_WRITE, op_stx   },  // STX d,Y
    [0x97] = { PAT_ZPY_WRITE, op_sax   },  // *SAX d,Y
    [0x98] = { PAT_IMPLIED,   op_tya   },  // TYA
    [0x99] = { PAT_ABY_WRITE, op_sta   },  // STA a,Y
    [0x9A] = { PAT_IMPLIED,   op_txs   },  // TXS
    [0x9D] = { PAT_ABX_WRITE, op_sta   },  // STA a,X

    [0xA0] = { PAT_IMMEDIATE, op_ldy   },  // LDY #
    [0xA1] = { PAT_IZX_READ,  op_lda   },  // LDA (d,X)
    [0xA2] = { PAT_IMMEDIATE, op_ldx   },  // LDX #
    [0xA3] = { PAT_IZX_READ,  op_lax   },  // *LAX (d,X)
    [0xA4] = { PAT_ZPG_READ,  op_ldy   },  // LDY d
    [0xA5] = { PAT_ZPG_READ,  op_lda   },  // LDA d
    [0xA6] = { PAT_ZPG_READ,  op_ldx   },  // LDX d
    [0xA7] = { PAT_ZPG_READ,  op_lax   },  // *LAX d
    [0xA8] = { PAT_IMPLIED,   op_tay   },  // TAY
    [0xA9] = { PAT_IMMEDIATE, op_lda   },  // LDA #
    [0xAA] = { PAT_IMPLIED,   op_tax   },  // TAX
    [0xAC] = { PAT_ABS_READ,  op_ldy   },  // LDY a
    [0xAD] = { PAT_ABS_READ,  op_lda   },  // LDA a
    [0xAE] = { PAT_ABS_READ,  op_ldx   },  // LDX a
    [0xAF] = { PAT_ABS_READ,  op_lax   },  // *LAX a

    [0xB0] = { PAT_BRANCH,    op_bcs   },  // BCS
    [0xB1] = { PAT_IZY_READ,  op_lda   },  // LDA (d),Y
    [0xB3] = { PAT_IZY_READ,  op_lax   },  // *LAX (d),Y
    [0xB4] = { PAT_ZPX_READ,  op_ldy   },  // LDY d,X
    [0xB5] = { PAT_ZPX_READ,  op_lda   },  // LDA d,X
    [0xB6] = { PAT_ZPY_READ,  op_ldx   },  // LDX d,Y
    [0xB7] = { PAT_ZPY_READ,  op_lax   },  // *LAX d,Y
    [0xB8] = { PAT_IMPLIED,   op_clv   },  // CLV
    [0xB9] = { PAT_ABY_READ,  op_lda   },  // LDA a,Y
    [0xBA] = { PAT_IMPLIED,   op_tsx   },  // TSX
    [0xBC] = { PAT_ABX_READ,  op_ldy   },  // LDY a,X
    [0xBD] = { PAT_ABX_READ,  op_lda   },  // LDA a,X
    [0xBE] = { PAT_ABY_READ,  op_ldx   },  // LDX a,Y
    [0xBF] = { PAT_ABY_READ,  op_lax   },  // *LAX a,Y

    [0xC0] = { PAT_IMMEDIATE, op_cpy   },  // CPY #
    [0xC1] = { PAT_IZX_READ,  op_cmp   },  // CMP (d,X)
    [0xC2] = { PAT_IMMEDIATE, op_nop   },  // *NOP #
    [0xC3] = { PAT_IZX_RMW,   op_dcp   },  // *DCP (d,X)
    [0xC4] = { PAT_ZPG_READ,  op_cpy   },  // CPY d
    [0xC5] = { PAT_ZPG_READ,  op_cmp   },  // CMP d
    [0xC6] = { PAT_ZPG_RMW,   op_dec   },  // DEC d
    [0xC7] = { PAT_ZPG_RMW,   op_dcp   },  // *DCP d
    [0xC8] = { PAT_IMPLIED,   op_iny   },  // INY
    [0xC9] = { PAT_IMMEDIATE, op_cmp   },  // CMP #
    [0xCA] = { PAT_IMPLIED,   op_dex   },  // DEX
    [0xCB] = { PAT_IMMEDIATE, op_axs   },  // *AXS #
    [0xCC] = { PAT_ABS_READ,  op_cpy   },  // CPY a
    [0xCD] = { PAT_ABS_READ,  op_cmp   },  // CMP a
    [0xCE] = { PAT_ABS_RMW,   op_dec   },  // DEC a
    [0xCF] = { PAT_ABS_RMW,   op_dcp   },  // *DCP a

    [0xD0] = { PAT_BRANCH,    op_bne   },  // BNE
    [0xD1] = { PAT_IZY_READ,  op_cmp   },  // CMP (d),Y
    [0xD3] = { PAT_IZY_RMW,   op_dcp   },  // *DCP (d),Y
    [0xD4] = { PAT_ZPX_READ,  op_nop   },  // *NOP d,X
    [0xD5] = { PAT_ZPX_READ,  op_cmp   },  // CMP d,X
    [0xD6] = { PAT_ZPX_RMW,   op_dec   },  // DEC d,X
    [0xD7] = { PAT_ZPX_RMW,   op_dcp   },  // *DCP d,X
    [0xD8] = { PAT_IMPLIED,   op_cld   },  // CLD
    [0xD9] = { PAT_ABY_READ,  op_cmp   },  // CMP a,Y
    [0xDA] = { PAT_IMPLIED,   op_nop   },  // *NOP
    [0xDB] = { PAT_ABY_RMW,   op_dcp   },  // *DCP a,Y
    [0xDC] = { PAT_ABX_READ,  op_nop   },  // *NOP a,X
    [0xDD] = { PAT_ABX_READ,  op_cmp   },  // CMP a,X
    [0xDE] = { PAT_ABX_RMW,   op_dec   },  // DEC a,X
    [0xDF] = { PAT_ABX_RMW,   op_dcp   },  // *DCP a,X

    [0xE0] = { PAT_IMMEDIATE, op_cpx   },  // CPX #
    [0xE1] = { PAT_IZX_READ,  op_sbc   },  // SBC (d,X)
    [0xE2] = { PAT_IMMEDIATE, op_nop   },  // *NOP #
    [0xE3] = { PAT_IZX_RMW,   op_isc   },  // *ISC (d,X)
    [0xE4] = { PAT_ZPG_READ,  op_cpx   },  // CPX d
    [0xE5] = { PAT_ZPG_READ,  op_sbc   },  // SBC d
    [0xE6] = { PAT_ZPG_RMW,   op_inc   },  // INC d
    [0xE7] = { PAT_ZPG_RMW,   op_isc   },  // *ISC d
    [0xE8] = { PAT_IMPLIED,   op_inx   },  // INX
    [0xE9] = { PAT_IMMEDIATE, op_sbc   },  // SBC #
    [0xEA] = { PAT_IMPLIED,   op_nop   },  // NOP
    [0xEB] = { PAT_IMMEDIATE, op_sbc   },  // *SBC # (unofficial, same as E9)
    [0xEC] = { PAT_ABS_READ,  op_cpx   },  // CPX a
    [0xED] = { PAT_ABS_READ,  op_sbc   },  // SBC a
    [0xEE] = { PAT_ABS_RMW,   op_inc   },  // INC a
    [0xEF] = { PAT_ABS_RMW,   op_isc   },  // *ISC a

    [0xF0] = { PAT_BRANCH,    op_beq   },  // BEQ
    [0xF1] = { PAT_IZY_READ,  op_sbc   },  // SBC (d),Y
    [0xF3] = { PAT_IZY_RMW,   op_isc   },  // *ISC (d),Y
    [0xF4] = { PAT_ZPX_READ,  op_nop   },  // *NOP d,X
    [0xF5] = { PAT_ZPX_READ,  op_sbc   },  // SBC d,X
    [0xF6] = { PAT_ZPX_RMW,   op_inc   },  // INC d,X
    [0xF7] = { PAT_ZPX_RMW,   op_isc   },  // *ISC d,X
    [0xF8] = { PAT_IMPLIED,   op_sed   },  // SED
    [0xF9] = { PAT_ABY_READ,  op_sbc   },  // SBC a,Y
    [0xFA] = { PAT_IMPLIED,   op_nop   },  // *NOP
    [0xFB] = { PAT_ABY_RMW,   op_isc   },  // *ISC a,Y
    [0xFC] = { PAT_ABX_READ,  op_nop   },  // *NOP a,X
    [0xFD] = { PAT_ABX_READ,  op_sbc   },  // SBC a,X
    [0xFE] = { PAT_ABX_RMW,   op_inc   },  // INC a,X
    [0xFF] = { PAT_ABX_RMW,   op_isc   },  // *ISC a,X
};
